manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: karnadii
      url-base: https://github.com/karnadii
  projects:
    - name: zmk
      remote: karnadii
      revision: 2.4
      import: app/west.yml
  self:
    path: zmk-config
